/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RMS;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author OBAID
 */
public class frmdashboard extends javax.swing.JFrame {
 
    /**
     * Creates new form frmdashboard
     */
    Timer updatetimer;
    int delay=100;
    String np="0";
    String sales="0";
    String purchase="0";
    String expense="0";
    public frmdashboard() throws FileNotFoundException {
        initComponents();
        this.setLocationRelativeTo(null);
        txtdate.setEditable(false);
      this.getContentPane().setBackground(new Color(255,255,255));
      btnlogout.setContentAreaFilled(false);
      DateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");
      Date date = new Date();
        txtdate.setText(dateFormat.format(date));
       updatetimer=new Timer(delay,new ActionListener(){
       @Override
           public void actionPerformed(ActionEvent e){
        String format="hh:mm:ss";
        DateFormat timeFormat = new SimpleDateFormat(format);
        Date time=new Date();
        lbltime.setText(timeFormat.format(time));
       }
       });
       updatetimer.start();
          File myObj1 = new File("Resources/TotalSales.txt");
        try ( Scanner myReader1 = new Scanner(myObj1)) {
            while (myReader1.hasNextLine()) {
                sales = (myReader1.nextLine());
            }
        }
         File myObj2 = new File("Resources/onlyFoodItems.txt");
        try ( Scanner myReader1 = new Scanner(myObj2)) {
            while (myReader1.hasNextLine()) {
                np = (myReader1.nextLine());
            }
        }
         File myObj3 = new File("Resources/purchasereporttotal.txt");
        try ( Scanner myReader1 = new Scanner(myObj3)) {
            while (myReader1.hasNextLine()) {
                purchase = (myReader1.nextLine());
            }
        }
           File myObj4 = new File("Resources/expensereporttotal.txt");
        try ( Scanner myReader1 = new Scanner(myObj4)) {
            while (myReader1.hasNextLine()) {
                expense = (myReader1.nextLine());
            }
        }
        lblnp.setText(np);
        lblsales.setText(sales);
        lblpurchase.setText(purchase);
        lblexpense.setText(expense);
        lblprofit.setText(String.valueOf(Double.parseDouble(lblsales.getText())-Double.parseDouble(lblpurchase.getText())-Double.parseDouble(lblexpense.getText())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btncategory = new javax.swing.JButton();
        btnfooditems = new javax.swing.JButton();
        btnexpense = new javax.swing.JButton();
        btnSalesinvoice = new javax.swing.JButton();
        btnsalesreport = new javax.swing.JButton();
        btnproductinvoice = new javax.swing.JButton();
        btnproductreport = new javax.swing.JButton();
        txtdate = new javax.swing.JTextField();
        lbltime = new javax.swing.JLabel();
        btnrefresh = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblnp = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblsales = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblpurchase = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lblexpense = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lblprofit = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowDeiconified(java.awt.event.WindowEvent evt) {
                formWindowDeiconified(evt);
            }
            public void windowIconified(java.awt.event.WindowEvent evt) {
                formWindowIconified(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Restaurant Managment System");

        btnlogout.setBackground(new java.awt.Color(0, 0, 0));
        btnlogout.setIcon(new javax.swing.ImageIcon("D:\\Restaurant Managment System Oop Project\\RMS\\Resources\\logout.png")); // NOI18N
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnlogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        btncategory.setBackground(new java.awt.Color(165, 99, 0));
        btncategory.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btncategory.setText("Category");
        btncategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncategoryActionPerformed(evt);
            }
        });

        btnfooditems.setBackground(new java.awt.Color(165, 99, 0));
        btnfooditems.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnfooditems.setText("Fooditems");
        btnfooditems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfooditemsActionPerformed(evt);
            }
        });

        btnexpense.setBackground(new java.awt.Color(165, 99, 0));
        btnexpense.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnexpense.setText("Expense");
        btnexpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexpenseActionPerformed(evt);
            }
        });

        btnSalesinvoice.setBackground(new java.awt.Color(165, 99, 0));
        btnSalesinvoice.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnSalesinvoice.setText("Sales invoice");
        btnSalesinvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesinvoiceActionPerformed(evt);
            }
        });

        btnsalesreport.setBackground(new java.awt.Color(165, 99, 0));
        btnsalesreport.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnsalesreport.setText("Sales Report");
        btnsalesreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalesreportActionPerformed(evt);
            }
        });

        btnproductinvoice.setBackground(new java.awt.Color(165, 99, 0));
        btnproductinvoice.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnproductinvoice.setText("Product invoice");
        btnproductinvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproductinvoiceActionPerformed(evt);
            }
        });

        btnproductreport.setBackground(new java.awt.Color(165, 99, 0));
        btnproductreport.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnproductreport.setText("Product Report");
        btnproductreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproductreportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnexpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalesinvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsalesreport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnproductinvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncategory, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(btnfooditems, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(btnproductreport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSalesinvoice, btncategory, btnexpense, btnfooditems, btnproductinvoice, btnproductreport, btnsalesreport});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btncategory, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnfooditems, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnexpense, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalesinvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsalesreport, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnproductinvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnproductreport, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSalesinvoice, btncategory, btnexpense, btnfooditems, btnproductinvoice, btnproductreport, btnsalesreport});

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 530));

        txtdate.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdate.setBorder(null);
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 200, 40));

        lbltime.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbltime.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbltime.setText("00:00:00");
        getContentPane().add(lbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 140, 40));

        btnrefresh.setBackground(new java.awt.Color(0, 0, 0));
        btnrefresh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnrefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnrefresh.setText("Refresh");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 90, 40));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        lblnp.setBackground(new java.awt.Color(204, 204, 255));
        lblnp.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblnp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnp.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblnp, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblnp, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 180, 140));

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("No of Products");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 180, 20));

        jPanel5.setBackground(new java.awt.Color(255, 153, 153));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Sales");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 180, 20));

        jPanel6.setBackground(new java.awt.Color(255, 204, 204));

        lblsales.setBackground(new java.awt.Color(255, 204, 204));
        lblsales.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblsales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsales.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblsales, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblsales, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 180, 140));

        jPanel7.setBackground(new java.awt.Color(255, 255, 102));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Purchase");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 180, 20));

        jPanel8.setBackground(new java.awt.Color(255, 255, 204));

        lblpurchase.setBackground(new java.awt.Color(255, 204, 204));
        lblpurchase.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblpurchase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpurchase.setText("0");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblpurchase, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblpurchase, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 180, 140));

        jPanel9.setBackground(new java.awt.Color(102, 255, 102));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Expense");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 180, 20));

        jPanel10.setBackground(new java.awt.Color(204, 255, 204));

        lblexpense.setBackground(new java.awt.Color(153, 255, 153));
        lblexpense.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblexpense.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblexpense.setText("0");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblexpense, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblexpense, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 180, 140));

        jPanel11.setBackground(new java.awt.Color(255, 153, 255));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Profit");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 180, 20));

        jPanel12.setBackground(new java.awt.Color(255, 204, 255));

        lblprofit.setBackground(new java.awt.Color(255, 204, 204));
        lblprofit.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblprofit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblprofit.setText("0");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblprofit, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblprofit, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 180, 140));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Inventory");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem1.setText("Category");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem2.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem2.setText("Fooditems");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Sales");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem3.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem3.setText("Sales invoice");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem4.setText("Sales report");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("Purchase");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem5.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem5.setText("Purchase invoice");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem6.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem6.setText("Purchase report");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        jMenu6.setBackground(new java.awt.Color(255, 255, 255));
        jMenu6.setText("Others");

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem7.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem7.setText("Expense");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_0, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem8.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem8.setText("Logout");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        DateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");
      Date date = new Date();
        txtdate.setText(dateFormat.format(date));
       updatetimer=new Timer(delay,new ActionListener(){
       @Override
           public void actionPerformed(ActionEvent e){
        String format="hh:mm:ss";
        DateFormat timeFormat = new SimpleDateFormat(format);
        Date time=new Date();
        lbltime.setText(timeFormat.format(time));
       }
       });
       updatetimer.start();
          File myObj1 = new File("Resources/TotalSales.txt");
        try ( Scanner myReader1 = new Scanner(myObj1)) {
            while (myReader1.hasNextLine()) {
                sales = (myReader1.nextLine());
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmdashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
         File myObj2 = new File("Resources/onlyFoodItems.txt");
        try ( Scanner myReader1 = new Scanner(myObj2)) {
            while (myReader1.hasNextLine()) {
                np = (myReader1.nextLine());
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmdashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
         File myObj3 = new File("Resources/purchasereporttotal.txt");
        try ( Scanner myReader1 = new Scanner(myObj3)) {
            while (myReader1.hasNextLine()) {
                purchase = (myReader1.nextLine());
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmdashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
           File myObj4 = new File("Resources/expensereporttotal.txt");
        try ( Scanner myReader1 = new Scanner(myObj4)) {
            while (myReader1.hasNextLine()) {
                expense = (myReader1.nextLine());
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmdashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        lblnp.setText(np);
        lblsales.setText(sales);
        lblpurchase.setText(purchase);
        lblexpense.setText(expense);
        lblprofit.setText(String.valueOf(Double.parseDouble(lblsales.getText())-Double.parseDouble(lblpurchase.getText())-Double.parseDouble(lblexpense.getText())));
    }//GEN-LAST:event_formWindowActivated

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
       
    }//GEN-LAST:event_formWindowGainedFocus

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void formWindowDeiconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeiconified

    }//GEN-LAST:event_formWindowDeiconified

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked

    private void formWindowIconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowIconified

    }//GEN-LAST:event_formWindowIconified

    private void btnsalesreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalesreportActionPerformed
        frmsalesreport obj1 = new frmsalesreport();
        //this.setEnabled(false);
        obj1.setVisible(true);
        obj1.setResizable(false);
    }//GEN-LAST:event_btnsalesreportActionPerformed

    private void btnSalesinvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesinvoiceActionPerformed
        frmsalesinvoice obj3 = null;
        try {
            obj3 = new frmsalesinvoice();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmdashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        //this.setEnabled(false);
        obj3.setVisible(true);
        obj3.setResizable(false);
    }//GEN-LAST:event_btnSalesinvoiceActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       Food obj=new Food();
       obj.setVisible(true);
       obj.setResizable(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            new frmsalesinvoice().setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmdashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       Items obj=new Items();
       obj.setVisible(true);
       obj.setResizable(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new frmsalesreport().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        dispose();
        new Loginform().setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void btncategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncategoryActionPerformed
        Food obj=new Food();
        obj.setVisible(true);
        obj.setResizable(false);
    }//GEN-LAST:event_btncategoryActionPerformed

    private void btnfooditemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfooditemsActionPerformed
       Items obj=new Items();
       obj.setVisible(true);
       obj.setResizable(false);
    }//GEN-LAST:event_btnfooditemsActionPerformed

    private void btnexpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexpenseActionPerformed
       Expense obj=new Expense();
       obj.setVisible(true);
       obj.setResizable(false);
    }//GEN-LAST:event_btnexpenseActionPerformed

    private void btnproductinvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductinvoiceActionPerformed
       Addpurchase obj=new Addpurchase();
       obj.setVisible(true);
       obj.setResizable(false);
    }//GEN-LAST:event_btnproductinvoiceActionPerformed

    private void btnproductreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductreportActionPerformed
        purchasereport obj=new purchasereport();
       obj.setVisible(true);
       obj.setResizable(false);
    }//GEN-LAST:event_btnproductreportActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
         dispose();
        new Loginform().setVisible(true);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
       DateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");
      Date date = new Date();
        txtdate.setText(dateFormat.format(date));
       updatetimer=new Timer(delay,new ActionListener(){
       @Override
           public void actionPerformed(ActionEvent e){
        String format="hh:mm:ss";
        DateFormat timeFormat = new SimpleDateFormat(format);
        Date time=new Date();
        lbltime.setText(timeFormat.format(time));
       }
       });
       updatetimer.start();
          File myObj1 = new File("Resources/TotalSales.txt");
        try ( Scanner myReader1 = new Scanner(myObj1)) {
            while (myReader1.hasNextLine()) {
                sales = (myReader1.nextLine());
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmdashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        File myObj2 = new File("Resources/onlyFoodItems.txt");
        try ( Scanner myReader1 = new Scanner(myObj2)) {
            while (myReader1.hasNextLine()) {
                np = (myReader1.nextLine());
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmdashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
         File myObj3 = new File("Resources/purchasereporttotal.txt");
        try ( Scanner myReader1 = new Scanner(myObj3)) {
            while (myReader1.hasNextLine()) {
                purchase = (myReader1.nextLine());
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmdashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
           File myObj4 = new File("Resources/expensereporttotal.txt");
        try ( Scanner myReader1 = new Scanner(myObj4)) {
            while (myReader1.hasNextLine()) {
                expense = (myReader1.nextLine());
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmdashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        lblnp.setText(np);
        lblsales.setText(sales);
        lblpurchase.setText(purchase);
        lblexpense.setText(expense);
        lblprofit.setText(String.valueOf(Double.parseDouble(lblsales.getText())-Double.parseDouble(lblpurchase.getText())-Double.parseDouble(lblexpense.getText())));
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       Addpurchase obj=new Addpurchase();
       obj.setVisible(true);
       obj.setResizable(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        purchasereport obj=new purchasereport();
       obj.setVisible(true);
       obj.setResizable(false);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       Expense obj=new Expense();
       obj.setVisible(true);
       obj.setResizable(false);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                frmdashboard obj2 = new frmdashboard();
                obj2.setVisible(true);
                obj2.setResizable(false);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(frmdashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalesinvoice;
    private javax.swing.JButton btncategory;
    private javax.swing.JButton btnexpense;
    private javax.swing.JButton btnfooditems;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnproductinvoice;
    private javax.swing.JButton btnproductreport;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnsalesreport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblexpense;
    private javax.swing.JLabel lblnp;
    private javax.swing.JLabel lblprofit;
    private javax.swing.JLabel lblpurchase;
    private javax.swing.JLabel lblsales;
    private javax.swing.JLabel lbltime;
    private javax.swing.JTextField txtdate;
    // End of variables declaration//GEN-END:variables
}
