/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RMS;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author OBAID
 */
public class frmpn extends javax.swing.JFrame {

    int x, y;

    /**
     * Creates new form frmpn
     */
    public frmpn() {
        initComponents();
        this.setLocationRelativeTo(null);
          this.getContentPane().setBackground(new Color(255,255,255));
        DefaultTableCellRenderer MyHeaderRender = new DefaultTableCellRenderer();
        MyHeaderRender.setBackground(new Color(0,0,0));
        MyHeaderRender.setForeground(new Color(255,255,255));
        tblps.getTableHeader().getColumnModel().getColumn(0).setHeaderRenderer(MyHeaderRender);
        tblps.getTableHeader().getColumnModel().getColumn(1).setHeaderRenderer(MyHeaderRender);
        tblps.getTableHeader().getColumnModel().getColumn(2).setHeaderRenderer(MyHeaderRender);
        tblps.getTableHeader().getColumnModel().getColumn(3).setHeaderRenderer(MyHeaderRender);
        txtps.requestFocus();
        try {
            BufferedReader br = new BufferedReader(new FileReader("Files/Fooditem.txt"));
            DefaultTableModel model = (DefaultTableModel) tblps.getModel();
            Object[] tableLines = br.lines().toArray();
            for (int i = 0; i < tableLines.length; i++) {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(",");
                model.addRow(dataRow);
            }

        } catch (Exception ex) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblps = new javax.swing.JTable();
        txtps = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tblps.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product id", "Product name", "Price", "Category"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpsMouseClicked(evt);
            }
        });
        tblps.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblpsKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblps);

        txtps.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtps.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtps.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtps.setNextFocusableComponent(tblps);
        txtps.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpsKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpsKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Search");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Products");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtps, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtps, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpsKeyPressed
            DefaultTableModel model = (DefaultTableModel) tblps.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(model);
        tblps.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txtps.getText().trim()));
    }//GEN-LAST:event_txtpsKeyPressed

    private void tblpsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpsMouseClicked
        int rows[]=this.tblps.getSelectedRows();

   for(int i=0;i<rows.length;i++)
   {
       int modelRow = tblps.convertRowIndexToModel(rows[i]);
       String value = tblps.getModel().getValueAt(modelRow, 0).toString();
       String value1 = tblps.getModel().getValueAt(modelRow, 1).toString();
       String value2= tblps.getModel().getValueAt(modelRow, 3).toString();
       String value3 = tblps.getModel().getValueAt(modelRow, 2).toString();
        frmsalesinvoice.txtpid.setText(value);
        frmsalesinvoice.txtpn.setText(value1);
        frmsalesinvoice.txtcat.setText(value2);
        frmsalesinvoice.txtprice.setText(value3);
   }
        dispose();
        
    }//GEN-LAST:event_tblpsMouseClicked

    private void txtpsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpsKeyTyped
         
    }//GEN-LAST:event_txtpsKeyTyped

    private void tblpsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblpsKeyPressed
      if (evt.getKeyCode() == KeyEvent.VK_ENTER )
      {
           int rows[]=this.tblps.getSelectedRows();

   for(int i=0;i<rows.length;i++)
   {
       int modelRow = tblps.convertRowIndexToModel(rows[i]);
       String value = tblps.getModel().getValueAt(modelRow, 0).toString();
       String value1 = tblps.getModel().getValueAt(modelRow, 1).toString();
       String value2= tblps.getModel().getValueAt(modelRow, 3).toString();
       String value3 = tblps.getModel().getValueAt(modelRow, 2).toString();
        frmsalesinvoice.txtpid.setText(value);
        frmsalesinvoice.txtpn.setText(value1);
        frmsalesinvoice.txtcat.setText(value2);
        frmsalesinvoice.txtprice.setText(value3);
   }
        dispose();
      }
    }//GEN-LAST:event_tblpsKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmpn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmpn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmpn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmpn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmpn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblps;
    private javax.swing.JTextField txtps;
    // End of variables declaration//GEN-END:variables
}
