/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RMS;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author saman
 */
public class Items extends javax.swing.JFrame {
  DefaultTableModel model;
    /**
     * Creates new form Items
     */
    public Items() {
        initComponents();
        this.setLocationRelativeTo(null);
        model = (DefaultTableModel) fooditem_tbl.getModel();
        category_list();

        this.getContentPane().setBackground(new Color(255, 255, 255));
        DefaultTableCellRenderer MyHeaderRender = new DefaultTableCellRenderer();
        MyHeaderRender.setBackground(new Color(0, 0, 0));
        MyHeaderRender.setForeground(new Color(255, 255, 255));
        fooditem_tbl.getTableHeader().getColumnModel().getColumn(0).setHeaderRenderer(MyHeaderRender);
        fooditem_tbl.getTableHeader().getColumnModel().getColumn(1).setHeaderRenderer(MyHeaderRender);
        fooditem_tbl.getTableHeader().getColumnModel().getColumn(2).setHeaderRenderer(MyHeaderRender);
        fooditem_tbl.getTableHeader().getColumnModel().getColumn(3).setHeaderRenderer(MyHeaderRender);
        fooditem_tbl.getTableHeader().getColumnModel().getColumn(4).setHeaderRenderer(MyHeaderRender);
    }
   public void blank() {
        id_txt.setText(null);
        itemname_txt.setText(null);
        price_txt.setText(null);
        category_cbox.setSelectedItem(null);
    }

    public static void category_list() {
        try {
            File myObj = new File("Resources/onlyFoodCategory.txt");
            if (myObj.createNewFile()) {
                System.out.println("File created: " + myObj.getName());
            } else {
                System.out.println("File already exists.");
            }

            Scanner myReader = new Scanner(myObj);
            while (myReader.hasNextLine()) {
                String data = myReader.nextLine();
                category_cbox.addItem(data);
            }
            myReader.close();
        } catch (IOException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        print_btn = new javax.swing.JButton();
        itemname_lbl = new javax.swing.JLabel();
        search_lbl = new javax.swing.JLabel();
        price_lbl = new javax.swing.JLabel();
        search_txt = new javax.swing.JTextField();
        category_lbl = new javax.swing.JLabel();
        reset_btn = new javax.swing.JButton();
        fooditem_pnl = new javax.swing.JScrollPane();
        fooditem_tbl = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        add_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        id_lbl = new javax.swing.JLabel();
        close_btn = new javax.swing.JButton();
        itemname_txt = new javax.swing.JTextField();
        category_cbox = new javax.swing.JComboBox<>();
        price_txt = new javax.swing.JTextField();
        update_btn = new javax.swing.JButton();
        id_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        print_btn.setIcon(new javax.swing.ImageIcon("D:\\Restaurant Managment System Oop Project\\RMS\\Resources\\printer.png")); // NOI18N
        print_btn.setText("Print");
        print_btn.setPreferredSize(new java.awt.Dimension(75, 25));
        print_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_btnActionPerformed(evt);
            }
        });
        print_btn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                print_btnKeyPressed(evt);
            }
        });

        itemname_lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemname_lbl.setText("Item Name");

        search_lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        search_lbl.setText("Search");

        price_lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        price_lbl.setText("Price");

        search_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        search_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_txtKeyReleased(evt);
            }
        });

        category_lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        category_lbl.setText("Category");

        reset_btn.setIcon(new javax.swing.ImageIcon("D:\\Restaurant Managment System Oop Project\\RMS\\Resources\\remove.png")); // NOI18N
        reset_btn.setText("Reset");
        reset_btn.setPreferredSize(new java.awt.Dimension(75, 25));
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });
        reset_btn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                reset_btnKeyPressed(evt);
            }
        });

        fooditem_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Price", "Category", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        fooditem_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fooditem_tblMouseClicked(evt);
            }
        });
        fooditem_tbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fooditem_tblKeyPressed(evt);
            }
        });
        fooditem_pnl.setViewportView(fooditem_tbl);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Food Items");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        add_btn.setIcon(new javax.swing.ImageIcon("D:\\Restaurant Managment System Oop Project\\RMS\\Resources\\plus (2).png")); // NOI18N
        add_btn.setText("Add");
        add_btn.setNextFocusableComponent(id_txt);
        add_btn.setPreferredSize(new java.awt.Dimension(75, 25));
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });
        add_btn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                add_btnKeyPressed(evt);
            }
        });

        delete_btn.setIcon(new javax.swing.ImageIcon("D:\\Restaurant Managment System Oop Project\\RMS\\Resources\\minus.png")); // NOI18N
        delete_btn.setText("Delete");
        delete_btn.setNextFocusableComponent(id_txt);
        delete_btn.setPreferredSize(new java.awt.Dimension(75, 25));
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        delete_btn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                delete_btnKeyPressed(evt);
            }
        });

        id_lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id_lbl.setText("ID");

        close_btn.setIcon(new javax.swing.ImageIcon("D:\\Restaurant Managment System Oop Project\\RMS\\Resources\\close.png")); // NOI18N
        close_btn.setText("Close");
        close_btn.setPreferredSize(new java.awt.Dimension(75, 25));
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnActionPerformed(evt);
            }
        });
        close_btn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                close_btnKeyPressed(evt);
            }
        });

        itemname_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        itemname_txt.setNextFocusableComponent(price_txt);

        category_cbox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        category_cbox.setNextFocusableComponent(add_btn);

        price_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        price_txt.setNextFocusableComponent(category_cbox);

        update_btn.setIcon(new javax.swing.ImageIcon("D:\\Restaurant Managment System Oop Project\\RMS\\Resources\\updated.png")); // NOI18N
        update_btn.setText("Update");
        update_btn.setNextFocusableComponent(id_txt);
        update_btn.setPreferredSize(new java.awt.Dimension(75, 25));
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        update_btn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                update_btnKeyPressed(evt);
            }
        });

        id_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        id_txt.setNextFocusableComponent(itemname_txt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(search_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(category_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(category_cbox, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(itemname_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(price_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(price_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(itemname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(id_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(reset_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(print_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fooditem_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itemname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemname_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(price_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(category_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(category_cbox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reset_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(147, 147, 147))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(search_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fooditem_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(print_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(14, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {add_btn, close_btn, delete_btn, print_btn, reset_btn, update_btn});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void print_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_btnActionPerformed
        try {
            fooditem_tbl.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Food.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_print_btnActionPerformed

    private void print_btnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_print_btnKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                fooditem_tbl.print();
            } catch (PrinterException ex) {
                Logger.getLogger(Food.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_print_btnKeyPressed

    private void search_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_txtKeyReleased

        TableRowSorter<DefaultTableModel> t4 = new TableRowSorter<>(model);
        fooditem_tbl.setRowSorter(t4);
        t4.setRowFilter(RowFilter.regexFilter("(?i)" + search_txt.getText().trim()));
        
    }//GEN-LAST:event_search_txtKeyReleased

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
        blank();
        id_txt.requestFocusInWindow();
    }//GEN-LAST:event_reset_btnActionPerformed

    private void reset_btnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reset_btnKeyPressed
        blank();
        id_txt.requestFocusInWindow();
    }//GEN-LAST:event_reset_btnKeyPressed

    private void fooditem_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fooditem_tblMouseClicked

        int row[] = this.fooditem_tbl.getSelectedRows();

        for (int i = 0; i < row.length; i++) {

            int modelRow = fooditem_tbl.convertRowIndexToModel(row[i]);
            String id = model.getValueAt(modelRow, 0).toString();
            String name = model.getValueAt(modelRow, 1).toString();
            String price = model.getValueAt(modelRow, 2).toString();
            String category = model.getValueAt(modelRow, 3).toString();
            id_txt.setText(id);
            itemname_txt.setText(name);
            price_txt.setText(price);
            category_cbox.setSelectedItem(category);

        }
    }//GEN-LAST:event_fooditem_tblMouseClicked

    private void fooditem_tblKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fooditem_tblKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            int row[] = this.fooditem_tbl.getSelectedRows();

            for (int i = 0; i < row.length; i++) {

                int modelRow = fooditem_tbl.convertRowIndexToModel(row[i]);
                String id = model.getValueAt(modelRow, 0).toString();
                String name = model.getValueAt(modelRow, 1).toString();
                String price = model.getValueAt(modelRow, 2).toString();
                String category = model.getValueAt(modelRow, 3).toString();
                id_txt.setText(id);
                itemname_txt.setText(name);
                price_txt.setText(price);
                category_cbox.setSelectedItem(category);

            }
        }
    }//GEN-LAST:event_fooditem_tblKeyPressed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed

        if (!(Pattern.matches("^[a-zA-Z ]+$", itemname_txt.getText()))) {
            JOptionPane.showMessageDialog(this, "Please enter a valid item name", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!(Pattern.matches("^[0-9]+$", id_txt.getText()))) {
            JOptionPane.showMessageDialog(this, "Please enter a valid ID", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!(Pattern.matches("^[0-9]+$", price_txt.getText()))) {
            JOptionPane.showMessageDialog(this, "Please enter a price", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (evt.getSource() == add_btn) {
            model.insertRow(model.getRowCount(), new Object[]{id_txt.getText(), itemname_txt.getText(), price_txt.getText(), category_cbox.getSelectedItem(), java.time.LocalDate.now()});
            blank();
        }
        try {
            File data = new File("Files/foodItem.txt");
            if (!data.exists()) {
                data.createNewFile();
            }

            try (FileWriter fw = new FileWriter(data.getAbsoluteFile())) {
                BufferedWriter bw = new BufferedWriter(fw);

                for (int i = 0; i < fooditem_tbl.getRowCount(); i++) {
                    for (int j = 0; j < fooditem_tbl.getColumnCount(); j++) {
                        bw.write(fooditem_tbl.getModel().getValueAt(i, j) + ",");
                    }
                    bw.write("\n");
                }
                bw.close();
            }
        } catch (IOException ex) {
            Logger.getLogger(Food.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            File data = new File("Resources/onlyFoodItems.txt");
            if (!data.exists()) {
                data.createNewFile();
            }

            FileWriter fw = new FileWriter(data.getAbsoluteFile());
            BufferedWriter bw = new BufferedWriter(fw);

            int i = 0;
            for (i = 1; i <= fooditem_tbl.getRowCount(); i++) {
            }
            bw.write(--i + "");

            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Food.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        blank();
        id_txt.requestFocusInWindow();
    }//GEN-LAST:event_add_btnActionPerformed

    private void add_btnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_add_btnKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!(Pattern.matches("^[a-zA-Z ]+$", itemname_txt.getText()))) {
                JOptionPane.showMessageDialog(this, "Please enter a valid item name", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (!(Pattern.matches("^[0-9]+$", id_txt.getText()))) {
                JOptionPane.showMessageDialog(this, "Please enter a valid ID", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (!(Pattern.matches("^[0-9]+$", price_txt.getText()))) {
                JOptionPane.showMessageDialog(this, "Please enter a price", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (evt.getSource() == add_btn) {
                model.insertRow(model.getRowCount(), new Object[]{id_txt.getText(), itemname_txt.getText(), price_txt.getText(), category_cbox.getSelectedItem(), java.time.LocalDate.now()});
                blank();
            }
            try {
                File data = new File("Files/foodItem.txt");
                if (!data.exists()) {
                    data.createNewFile();
                }

                try (FileWriter fw = new FileWriter(data.getAbsoluteFile())) {
                    BufferedWriter bw = new BufferedWriter(fw);

                    for (int i = 0; i < fooditem_tbl.getRowCount(); i++) {
                        for (int j = 0; j < fooditem_tbl.getColumnCount(); j++) {
                            bw.write(fooditem_tbl.getModel().getValueAt(i, j) + ",");
                        }
                        bw.write("\n");
                    }
                    bw.close();
                }
            } catch (IOException ex) {
                Logger.getLogger(Food.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try {
            File data = new File("Resources/onlyFoodItems.txt");
            if (!data.exists()) {
                data.createNewFile();
            }

            FileWriter fw = new FileWriter(data.getAbsoluteFile());
            BufferedWriter bw = new BufferedWriter(fw);

            int i = 0;
            for (i = 1; i <= fooditem_tbl.getRowCount(); i++) {
            }
            bw.write(--i + "");

            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Food.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        blank();
        id_txt.requestFocusInWindow();
    }//GEN-LAST:event_add_btnKeyPressed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed

        if (fooditem_tbl.getSelectedRow() != -1) {
            int modelRow = fooditem_tbl.convertRowIndexToModel(fooditem_tbl.getSelectedRow());
                model.removeRow(modelRow);
                search_txt.setText("");
                id_txt.requestFocus();
                 TableRowSorter<DefaultTableModel> t4 = new TableRowSorter<>(model);
        fooditem_tbl.setRowSorter(t4);
        t4.setRowFilter(null);
        }
        try {
            File data = new File("Files/foodItem.txt");
            if (!data.exists()) {
                data.createNewFile();
            }

            try (FileWriter fw = new FileWriter(data.getAbsoluteFile())) {
                BufferedWriter bw = new BufferedWriter(fw);

                for (int i = 0; i < fooditem_tbl.getRowCount(); i++) {
                    for (int j = 0; j < fooditem_tbl.getColumnCount(); j++) {
                        bw.write(fooditem_tbl.getModel().getValueAt(i, j) + ",");
                    }
                    bw.write("\n");
                }
                bw.close();
            }
        } catch (IOException ex) {
            Logger.getLogger(Food.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            File data = new File("Resources/onlyFoodItems.txt");
            if (!data.exists()) {
                data.createNewFile();
            }

            FileWriter fw = new FileWriter(data.getAbsoluteFile());
            BufferedWriter bw = new BufferedWriter(fw);

            int i = 0;
            for (i = 1; i <= fooditem_tbl.getRowCount(); i++) {
            }
            bw.write(--i + "");

            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Food.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        blank();
    }//GEN-LAST:event_delete_btnActionPerformed

    private void delete_btnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_delete_btnKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (fooditem_tbl.getSelectedRow() != -1) {
                int modelRow = fooditem_tbl.convertRowIndexToModel(fooditem_tbl.getSelectedRow());
                model.removeRow(modelRow);
                search_txt.setText("");
                id_txt.requestFocus();
                 TableRowSorter<DefaultTableModel> t4 = new TableRowSorter<>(model);
        fooditem_tbl.setRowSorter(t4);
        t4.setRowFilter(null);
            }
            try {
                File data = new File("Files/foodItem.txt");
                if (!data.exists()) {
                    data.createNewFile();
                }

                try (FileWriter fw = new FileWriter(data.getAbsoluteFile())) {
                    BufferedWriter bw = new BufferedWriter(fw);

                    for (int i = 0; i < fooditem_tbl.getRowCount(); i++) {
                        for (int j = 0; j < fooditem_tbl.getColumnCount(); j++) {
                            bw.write(fooditem_tbl.getModel().getValueAt(i, j) + ",");
                        }
                        bw.write("\n");
                    }
                    bw.close();
                }
            } catch (IOException ex) {
                Logger.getLogger(Food.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                File data = new File("Resources/onlyFoodItems.txt");
                if (!data.exists()) {
                    data.createNewFile();
                }

                FileWriter fw = new FileWriter(data.getAbsoluteFile());
                BufferedWriter bw = new BufferedWriter(fw);

                int i = 0;
                for (i = 1; i <= fooditem_tbl.getRowCount(); i++) {
                }
                bw.write(--i + "");

                bw.close();
                fw.close();
            } catch (IOException ex) {
                Logger.getLogger(Food.class.getName()).log(Level.SEVERE, null, ex);
                ex.printStackTrace();
            }
            blank();
        }
    }//GEN-LAST:event_delete_btnKeyPressed

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnActionPerformed
        dispose();
    }//GEN-LAST:event_close_btnActionPerformed

    private void close_btnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_close_btnKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dispose();
        }
    }//GEN-LAST:event_close_btnKeyPressed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed

        if (fooditem_tbl.getSelectedRowCount() == 1) {
            String id = id_txt.getText();
            String name = itemname_txt.getText();
            String price = price_txt.getText();
            String category = category_cbox.getSelectedItem().toString();

            model.setValueAt(id, fooditem_tbl.getSelectedRow(), 0);
            model.setValueAt(name, fooditem_tbl.getSelectedRow(), 1);
            model.setValueAt(price, fooditem_tbl.getSelectedRow(), 2);
            model.setValueAt(category, fooditem_tbl.getSelectedRow(), 3);
            JOptionPane.showMessageDialog(this, "updated!");
        } else {
            if (fooditem_tbl.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "no values in table");
            } else {
                JOptionPane.showMessageDialog(this, "select a single row to update");
            }

        }
        try {
            File data = new File("Files/foodItem.txt");
            if (!data.exists()) {
                data.createNewFile();
            }

            try (FileWriter fw = new FileWriter(data.getAbsoluteFile())) {
                BufferedWriter bw = new BufferedWriter(fw);

                for (int i = 0; i < fooditem_tbl.getRowCount(); i++) {
                    for (int j = 0; j < fooditem_tbl.getColumnCount(); j++) {
                        bw.write(fooditem_tbl.getModel().getValueAt(i, j) + ",");
                    }
                    bw.write("\n");
                }
                bw.close();
            }
        } catch (IOException ex) {
            Logger.getLogger(Food.class.getName()).log(Level.SEVERE, null, ex);
        }

        blank();
    }//GEN-LAST:event_update_btnActionPerformed

    private void update_btnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_update_btnKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (fooditem_tbl.getSelectedRowCount() == 1) {
                String id = id_txt.getText();
                String name = itemname_txt.getText();
                String price = price_txt.getText();
                String category = category_cbox.getSelectedItem().toString();

                model.setValueAt(id, fooditem_tbl.getSelectedRow(), 0);
                model.setValueAt(name, fooditem_tbl.getSelectedRow(), 1);
                model.setValueAt(price, fooditem_tbl.getSelectedRow(), 2);
                model.setValueAt(category, fooditem_tbl.getSelectedRow(), 3);
                JOptionPane.showMessageDialog(this, "updated!");
            } else {
                if (fooditem_tbl.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(this, "no values in table");
                } else {
                    JOptionPane.showMessageDialog(this, "select a single row to update");
                }
            }
            try {
                File data = new File("Files/foodItem.txt");
                if (!data.exists()) {
                    data.createNewFile();
                }

                try (FileWriter fw = new FileWriter(data.getAbsoluteFile())) {
                    BufferedWriter bw = new BufferedWriter(fw);

                    for (int i = 0; i < fooditem_tbl.getRowCount(); i++) {
                        for (int j = 0; j < fooditem_tbl.getColumnCount(); j++) {
                            bw.write(fooditem_tbl.getModel().getValueAt(i, j) + ",");
                        }
                        bw.write("\n");
                    }
                    bw.close();
                }
            } catch (IOException ex) {
                Logger.getLogger(Food.class.getName()).log(Level.SEVERE, null, ex);
            }

            blank();
        }
    }//GEN-LAST:event_update_btnKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
         if (model.getRowCount() <= 0) {
            try {
                File myObj = new File("Files/foodItem.txt");
                if (myObj.createNewFile()) {
                    System.out.println("File created: " + myObj.getName());
                } else {
                    System.out.println("File already exists.");
                }

                try (Scanner myReader = new Scanner(myObj)) {
                    while (myReader.hasNextLine()) {
                        String data = myReader.nextLine();
                        model.insertRow(model.getRowCount(), new Object[]{data.split(",")[0], data.split(",")[1], data.split(",")[2], data.split(",")[3], data.split(",")[4]});
                    }
                }
            } catch (IOException e) {
                System.out.println("An error occurred.");
                e.printStackTrace();
            }
        }
        blank();
        id_txt.requestFocusInWindow();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Items().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    public static javax.swing.JComboBox<String> category_cbox;
    private javax.swing.JLabel category_lbl;
    private javax.swing.JButton close_btn;
    private javax.swing.JButton delete_btn;
    private javax.swing.JScrollPane fooditem_pnl;
    private javax.swing.JTable fooditem_tbl;
    private javax.swing.JLabel id_lbl;
    private javax.swing.JTextField id_txt;
    private javax.swing.JLabel itemname_lbl;
    private javax.swing.JTextField itemname_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel price_lbl;
    private javax.swing.JTextField price_txt;
    private javax.swing.JButton print_btn;
    private javax.swing.JButton reset_btn;
    private javax.swing.JLabel search_lbl;
    private javax.swing.JTextField search_txt;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
