/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RMS;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author saman
 */
public class purchasereport extends javax.swing.JFrame {

    
    
    /**
     * Creates new form purchasereport
     */
  
    public purchasereport()     
    {
        initComponents();
         DefaultTableCellRenderer MyHeaderRender = new DefaultTableCellRenderer();
        MyHeaderRender.setForeground(new Color(255,255,255));
       tbl.getTableHeader().getColumnModel().getColumn(0).setHeaderRenderer(MyHeaderRender);
       tbl.getTableHeader().getColumnModel().getColumn(1).setHeaderRenderer(MyHeaderRender);
       tbl.getTableHeader().getColumnModel().getColumn(2).setHeaderRenderer(MyHeaderRender);
       tbl.getTableHeader().getColumnModel().getColumn(3).setHeaderRenderer(MyHeaderRender);
       tbl.getTableHeader().getColumnModel().getColumn(4).setHeaderRenderer(MyHeaderRender);
       tbl.getTableHeader().getColumnModel().getColumn(5).setHeaderRenderer(MyHeaderRender);
       tbl.getTableHeader().getColumnModel().getColumn(6).setHeaderRenderer(MyHeaderRender);
       tbl.getTableHeader().getColumnModel().getColumn(7).setHeaderRenderer(MyHeaderRender);
         MyHeaderRender.setBackground(new Color(0,0,0));
      
      
      
    }
  
  
        private void printbutton() 
  {
       try {
             // TODO add your handling code here:
           tbl.print(); 
         } 
       catch (PrinterException ex) {
               System.out.println("An error occurred.");
         }
           
  }
    
      private void add()
  {
       int total=0;
        for(int i=0; i<tbl.getRowCount();i++)
        {
            total=total+Integer.parseInt(tbl.getValueAt(i, 5).toString().trim());
        }
        totaltxt.setText(Integer.toString(total).trim());
  }
     
 private void readfile()        
 {
     DefaultTableModel model=(DefaultTableModel)tbl.getModel();
     if (model.getRowCount()<= 0)
     {
    try {
            File Obj = new File("Files/purchasereport.txt");
            if (Obj.createNewFile()) {
                System.out.println("File created: " + Obj.getName());
            } else {
                System.out.println("File already exists.");
            }
   
            Scanner Reader = new Scanner(Obj);
            while (Reader.hasNextLine()) {
                String data = Reader.nextLine();
                model.insertRow(model.getRowCount(), new Object[]{data.split(",")[0], data.split(",")[1], data.split(",")[2],data.split(",")[3],data.split(",")[4],data.split(",")[5],data.split(",")[6],data.split(",")[7]});
            }
            Reader.close();
        } catch (IOException e) {
            System.out.println("An error occurred.");
        }
     }
 }
   private void totalfile()
  {
      
           try{
             File file=new File("Resources/purchasereporttotal.txt");
        FileWriter writter = new FileWriter(file,true);
        BufferedWriter  b1=new BufferedWriter(writter);
        String total=totaltxt.getText();
          b1.write(total);
                b1.close();
              writter.close();   
           }
           catch(IOException ex)
        {
        JOptionPane.showMessageDialog(null,"Error");
        }
      
  }

 private void savefile(){
   try{
        File file=new File("Files/purchasereport.txt");
        FileWriter writter = new FileWriter(file,true);
        BufferedWriter  b1=new BufferedWriter(writter);
        for(int i=0;i<tbl.getRowCount(); i++)
        { for(int j=0;j<tbl.getColumnCount();j++)
            {
                b1.write((String)tbl.getModel().getValueAt(i,j)+",");
               
            }
        b1.write("\n");
        }
        b1.close();
        writter.close();
        
        }
        catch(IOException ex)
        {
        JOptionPane.showMessageDialog(null,"Error");
        }
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        purchasereportlbl = new javax.swing.JLabel();
        searchtxt = new javax.swing.JTextField();
        searchlbl = new javax.swing.JLabel();
        printbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        closebtn = new javax.swing.JButton();
        totallbl = new javax.swing.JLabel();
        totaltxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Client name", "Item name", "price", "Qty", "NetAmount", "Detail", "Date"
            }
        ));
        tbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        purchasereportlbl.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        purchasereportlbl.setForeground(new java.awt.Color(255, 255, 255));
        purchasereportlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        purchasereportlbl.setText("Purchase Report");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(purchasereportlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(purchasereportlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        searchtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        searchtxt.setNextFocusableComponent(deletebtn);
        searchtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchtxtMouseClicked(evt);
            }
        });
        searchtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchtxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchtxtKeyReleased(evt);
            }
        });

        searchlbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchlbl.setForeground(new java.awt.Color(0, 51, 51));
        searchlbl.setText("SEARCH");

        printbtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        printbtn.setIcon(new javax.swing.ImageIcon("D:\\Restaurant Managment System Oop Project\\RMS\\Resources\\printer.png")); // NOI18N
        printbtn.setText("Print");
        printbtn.setNextFocusableComponent(closebtn);
        printbtn.setPreferredSize(new java.awt.Dimension(77, 25));
        printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbtnActionPerformed(evt);
            }
        });
        printbtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                printbtnKeyPressed(evt);
            }
        });

        deletebtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deletebtn.setIcon(new javax.swing.ImageIcon("D:\\Restaurant Managment System Oop Project\\RMS\\Resources\\minus.png")); // NOI18N
        deletebtn.setText("Delete");
        deletebtn.setNextFocusableComponent(printbtn);
        deletebtn.setPreferredSize(new java.awt.Dimension(89, 25));
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        deletebtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                deletebtnKeyPressed(evt);
            }
        });

        closebtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        closebtn.setIcon(new javax.swing.ImageIcon("D:\\Restaurant Managment System Oop Project\\RMS\\Resources\\close.png")); // NOI18N
        closebtn.setText("Close");
        closebtn.setNextFocusableComponent(searchtxt);
        closebtn.setPreferredSize(new java.awt.Dimension(81, 25));
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        closebtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                closebtnKeyPressed(evt);
            }
        });

        totallbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        totallbl.setText("Total");

        totaltxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        totaltxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totaltxtMouseClicked(evt);
            }
        });
        totaltxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                totaltxtKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(searchlbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(printbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(closebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totallbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closebtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totallbl)
                    .addComponent(totaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {closebtn, deletebtn, printbtn});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
       
        dispose();
    }//GEN-LAST:event_closebtnActionPerformed

    private void searchtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchtxtMouseClicked
        
        searchtxt.setText("");

    }//GEN-LAST:event_searchtxtMouseClicked

    private void searchtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtxtKeyReleased
        String txt=searchtxt.getText();
                  DefaultTableModel m1=(DefaultTableModel) tbl.getModel();
        TableRowSorter<DefaultTableModel> t4=new TableRowSorter<DefaultTableModel>(m1);
        tbl.setRowSorter(t4);
        if (txt.length()==0) {
            t4.setRowFilter(null);
        }
        else{
        t4.setRowFilter(RowFilter.regexFilter(searchtxt.getText().trim()));
        }
    }//GEN-LAST:event_searchtxtKeyReleased

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
     
      DefaultTableModel model=(DefaultTableModel) tbl.getModel();
           try{
             int modelRow = tbl.convertRowIndexToModel(tbl.getSelectedRow());
                model.removeRow(modelRow);
                searchtxt.setText(null);
                searchtxt.requestFocus();
                DefaultTableModel m1=(DefaultTableModel) tbl.getModel();
        TableRowSorter<DefaultTableModel> t4=new TableRowSorter<DefaultTableModel>(m1);
        tbl.setRowSorter(t4);
        t4.setRowFilter(null);
           }
           catch (Exception ex)
           {
               JOptionPane.showMessageDialog(null, ex);
   
    } 
       File myObj = new File("Files/purchasereport.txt"); 
         myObj.delete();
         savefile();
         File Obj = new File("Resources/purchasereporttotal.txt"); 
            Obj.delete();
            add();
            totalfile();                  
    }//GEN-LAST:event_deletebtnActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
     readfile();
     add();
     add();
      File Obj = new File("Resources/purchasereporttotal.txt"); 
      Obj.delete();
     totalfile();
   
    }//GEN-LAST:event_formWindowActivated

    private void printbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbtnActionPerformed
        // TODO add your handling code here:
        printbutton();
    }//GEN-LAST:event_printbtnActionPerformed

    private void totaltxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totaltxtMouseClicked

    }//GEN-LAST:event_totaltxtMouseClicked

    private void deletebtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deletebtnKeyPressed
     
          if (evt.getKeyCode() == KeyEvent.VK_ENTER){
              
      DefaultTableModel model=(DefaultTableModel) tbl.getModel();
           try{
             int modelRow = tbl.convertRowIndexToModel(tbl.getSelectedRow());
                model.removeRow(modelRow);
                searchtxt.setText(null);
                searchtxt.requestFocus();
                DefaultTableModel m1=(DefaultTableModel) tbl.getModel();
        TableRowSorter<DefaultTableModel> t4=new TableRowSorter<DefaultTableModel>(m1);
        tbl.setRowSorter(t4);
        t4.setRowFilter(null);
           }
           catch (Exception ex)
           {
               JOptionPane.showMessageDialog(null, ex);
   
    } 
       File myObj = new File("Files/purchasereport.txt"); 
         myObj.delete();
         savefile();
         File Obj = new File("Resources/purchasereporttotal.txt"); 
            Obj.delete();
            add();
            totalfile();
              
      }
    }//GEN-LAST:event_deletebtnKeyPressed

    private void printbtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_printbtnKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER){
           printbutton();
      }
    }//GEN-LAST:event_printbtnKeyPressed

    private void closebtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_closebtnKeyPressed
          if (evt.getKeyCode() == KeyEvent.VK_ENTER){
           dispose();
      }
    }//GEN-LAST:event_closebtnKeyPressed

    private void tblKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblKeyPressed
 
    }//GEN-LAST:event_tblKeyPressed

    private void searchtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtxtKeyPressed
             String txt=searchtxt.getText();
                  DefaultTableModel m1=(DefaultTableModel) tbl.getModel();
        TableRowSorter<DefaultTableModel> t4=new TableRowSorter<DefaultTableModel>(m1);
        tbl.setRowSorter(t4);
        if (txt.length()==0) {
            t4.setRowFilter(null);
        }
        else{
        t4.setRowFilter(RowFilter.regexFilter(searchtxt.getText().trim()));
        }
    }//GEN-LAST:event_searchtxtKeyPressed

    private void totaltxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totaltxtKeyPressed
      if (evt.getKeyCode() == KeyEvent.VK_ENTER)
      {
             add();
        totalfile(); 
      }
    }//GEN-LAST:event_totaltxtKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(purchasereport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(purchasereport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(purchasereport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(purchasereport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new purchasereport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closebtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printbtn;
    private javax.swing.JLabel purchasereportlbl;
    private javax.swing.JLabel searchlbl;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JTable tbl;
    private javax.swing.JLabel totallbl;
    private javax.swing.JTextField totaltxt;
    // End of variables declaration//GEN-END:variables
}
